apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
  - name: {{ .Values.app }}-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: {{ .Values.nodeport }}