apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  type: NodePort
  selector:
    app: fastapi-app
  ports:
  - name: fastapi-app-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007